name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

      - name: Build Test
        run: npm run build-test

      - name: Test
        run: npm run test
